## 2: Unisex names
## 3: Read the file into string
### Instructions
Use the open() function to return a File object with the parameters:

* r for read mode
* dq_unisex_names.csv for the file name
Then use the read() method of the File object to read the file into a string. Assign that string to a variable named data.

In [1]:
f = open("dq_unisex_names.csv", "r")
data = f.read()
print(data)

Casey,176544.328149
Riley,154860.66517300002
Jessie,136381.830656
Jackie,132928.78874000002
Avery,121797.41951600001
Jaime,109870.18729000002
Peyton,94896.39521599999
Kerry,88963.92625
Jody,80400.519199
Kendall,79210.873961
Payton,64151.630388
Skyler,53486.390419
Frankie,51288.068109
Pat,44781.602373
Quinn,41920.940058
Harley,41237.565743
Reese,36360.520613
Robbie,32636.047648000003
Tommie,29528.793818000002
Justice,27350.56457
Kris,24955.811341999997
Carey,24790.097053999998
Emerson,24167.154361
Blair,23160.101097
Amari,22296.161372
Elisha,22184.559374
Sage,21336.062278
Emery,18844.118877
Stevie,18665.219122
Rowan,18367.420464
Ollie,17889.750339
Shea,16768.891880000003
Jaylin,15093.192038999998
Phoenix,14841.367875999998
Charley,12546.265781999999
Armani,12541.667755
Devyn,12515.023073999999
Ivory,11908.580714
Kendal,11841.403479999999
Baby,11132.855753
Mckinley,10972.533414
Finley,10194.618867000001
Milan,9971.955937
Tory,9837.844335
Shay,9444.894035
Shiloh,8999.08523
Lavern,8776.346296
Sky,8386.640072
Reilly,8300.824693
Leighton,8281.601797
Santana,7922.713789
Arden,7773.147359999999
Campbell,7728.956865000001
Channing,7626.335577
Kamari,7584.893909
Alva,7496.35069
Clair,7148.894728
Lavon,7107.834786
Kenyatta,7063.611274
Britt,6852.95455
Vernell,6729.462903000001
Michal,6558.698679
Austyn,6228.961464999999
Rian,6139.851240999999
Dominque,6101.13501
Remy,6094.667878
Jammie,6013.444775
Ricki,5847.272146
Jordin,5770.788278
Trinidad,5747.944235
Ryley,5685.538724
Carrol,5513.606968
Landry,5449.51046
Lorin,5428.15538
Yael,5232.374916
Codi,4805.328209
Sloan,4796.882097
Jael,4472.71492
Kodi,4428.704313
Azariah,4420.560847
Dakotah,4388.8520229999995
Lorenza,4249.273719
Artie,4230.139897
Maxie,4123.46784
Torey,4058.5889740000002
Tai,4017.9162969999998
Kalani,4012.3161229999996
Codie,3998.8169869999997
Storm,3960.5374460000003
Jaedyn,3913.0768840000005
Merritt,3843.5606700000003
Allyn,3801.3328060000003
Jourdan,3781.556602
Yuri,3774.699243
Ellery,3738.814883
Oakley,3728.7983289999997
Gentry,3703.829157
Ellison,3651.546836
Arin,3634.974321
Sol,3624.9805439999996
Carrington,3616.3836
Dell,3615.0332759999997
Carlin,3554.951422
Lennie,3533.447279
Dru,3445.961147
Alpha,3406.676728
Kiran,3405.6976219999997
Tristyn,3336.366181
Camdyn,3274.913501
Krishna,3270.049176
Demetrice,3200.883393
Berkley,3184.6592739999996
Linden,3155.870202
Mikah,3094.0632379999997
Parris,3064.315071
Kalin,3021.240034
Kary,3020.9687059999997
Arie,3014.1230010000004
Aries,2964.7565329999998
Rio,2960.4438010000003
Sutton,2930.892868
Rhyan,2900.188369
Isa,2895.497837
Arlyn,2893.945006
Karsen,2872.427405
Seneca,2856.367471
Callan,2809.37665
Garnett,2797.598866
Micaiah,2749.93498
Christan,2684.978836
Aris,2549.033763
Tylar,2540.224111
Brighton,2534.958718
Merlyn,2500.628691
Kimani,2492.6957780000002
Salem,2484.362235
Barrie,2480.799063
Braylin,2476.689792
Charly,2473.36083
Ocean,2470.958543
Ara,2398.501272
Deane,2395.830649
Andree,2375.252032
Natividad,2343.4819039999998
Ardell,2327.065702
Divine,2322.744419
Ocie,2299.2449699999997
Lakota,2298.545252
Ashtin,2291.99335
Larkin,2267.588897
Kamdyn,2266.0110670000004
Waverly,2239.462468
Claudie,2203.6044690000003
Lannie,2182.972994
Vernie,2155.660129
Adair,2154.719944
Kaidyn,2139.577902
Verdell,2133.742154
Jae,2106.066765
Aven,2090.0594969999997
Kodie,2069.6383920000003
Shalom,2060.5958739999996
Daylin,2036.196151
Osiris,1997.239288
Dwan,1990.6460379999999
Lashaun,1977.848391
Ashten,1969.6975940000002
Dann,1959.4458739999998
Shai,1950.9917050000001
Teegan,1945.936273
Micha,1927.9759010000002
Tobie,1921.1876350000002
Jaelin,1910.944988
Marlowe,1893.8144550000002
Kareen,1865.710053
Ryen,1827.6550739999998
Marquette,1795.238032
Joell,1787.3188850000001
Adel,1776.564727
Golden,1763.136515
An,1746.029349
Ossie,1740.230779
Stephane,1724.789877
Vinnie,1711.276531
Armoni,1707.359443
Berlin,1675.592169
Thanh,1671.332281
Jimi,1666.012608
Linn,1654.7473220000002
Marvis,1653.1578
Tam,1647.93815
Kaylon,1644.939332
Kylin,1642.510785
Lajuan,1642.21941
Cameran,1611.747981
Shamari,1601.241909
Teddie,1595.122202
Laramie,1594.6312050000001
Ricci,1585.3125699999998
Jule,1555.296916
Cedar,1552.70581
Drue,1547.492989
Shade,1544.8814300000001
Jeryl,1538.032514
Taylen,1535.983379
Devonne,1534.988374
Delane,1525.850038
Arnell,1518.343435
Earlie,1510.680394
Tenzin,1464.873785
Kendel,1464.373914
Arlis,1462.0830939999998
Ashby,1459.2234050000002
Shia,1450.051376
Berkeley,1447.964706
Lin,1434.757899
Freedom,1419.5886619999999
Rylin,1405.565656
Aaryn,1391.6754779999999
Mykah,1378.630611
Shaya,1373.0472439999999
Tanis,1363.088001
Chancey,1357.860017
Jaidan,1353.840217
Jaydyn,1344.5675099999999
Kaedyn,1342.7232900000001
Talyn,1333.103591
Le,1323.979515
Hartley,1321.569286
Avon,1318.747786
Finnley,1313.456526
Schyler,1311.4051470000002
Rennie,1307.9576880000002
Aly,1298.699031
Kaydin,1293.967349
Camari,1292.5736140000001
Clemmie,1288.247856
Payson,1280.568167
Anay,1278.8241990000001
Devine,1270.283725
Terryl,1263.728601
Bao,1262.070243
Tru,1259.054676
Indiana,1241.572392
Evyn,1234.8999900000001
Deniz,1226.69535
Emari,1223.375248
Davi,1218.88119
True,1201.182194
De,1198.993461
Samar,1195.441393
Kriston,1194.67094
Lian,1191.954576
Brittan,1182.2318289999998
Torre,1176.840612
Shawne,1173.5104390000001
Kailen,1172.8998589999999
Aundra,1172.128503
Halen,1151.043395
Yuki,1144.030879
Marshell,1133.685172
Rivers,1130.701023
Jaziah,1129.100128
Amaree,1110.775383
Mycah,1110.674706
Toy,1108.941987
Tien,1107.223237
Adi,1098.5954160000001
Callahan,1097.1943130000002
Jazz,1093.761948
Reign,1090.493726
Burnice,1082.020651
Jamy,1080.584735
Lavaughn,1073.002013
Adrean,1069.9825130000002
Cache,1066.235232
Britain,1065.194805
Dalyn,1058.212286
Dondi,1055.7544970000001
Dallis,1055.194322
Nazareth,1049.117378
Nieves,1043.052359
Jireh,1040.386483
Collen,1039.818143
Onyx,1034.6819150000001
Raynell,1033.123788
Sonnie,1029.946621
Lyrik,1021.240142
Marice,1011.1573080000001
Lexington,1006.492185
Chi,1000.5135310000001
Eliyah,999.527175
Tonnie,989.2398619999999
Teagen,979.78441
Rudi,970.191498
Kamani,953.5662130000001
Han,951.241973
Jerre,950.8749849999999
Alika,947.321531
Monta,941.0637960000001
Jaydn,935.74131
Hadyn,926.30121
Kem,914.46861
Terrin,910.7775
Wisdom,909.725025
Natale,901.864284
Rossie,892.806341
Lugene,888.284575
Rebel,884.024521
Blayke,882.2342789999999
Donyell,872.649431
Myrl,869.491606
Kaelen,862.728436
Miko,851.474358
Elza,847.5763019999999
Kriss,835.6900009999999
Shadow,825.52436
Raylen,818.709884
Ramey,811.497395
Jaryn,806.5214070000001
Laren,804.308316
Leverne,802.818101
Khali,802.633638
Reiley,800.3377360000001
Jaydee,798.057272
Luan,797.245459
Reily,796.2872629999999
Caidyn,794.561122
Kaylor,794.271472
Juel,790.093471
Amrit,786.642927
Rayn,784.341578
Arien,782.936684
Britten,777.750504
Bela,760.563821
Arliss,758.632888
Aziah,758.4975969999999
Lonie,755.868642
Pasha,748.990463
Caylen,748.902375
Talin,745.096319
Shaune,741.347119
Valen,735.983288
Ozie,735.766434
Dung,735.265634
Avry,731.426697
Zamari,729.95515
Kam,728.774296
Ronit,726.408001
Kelin,719.439015
Teigan,714.664818
Sun,714.643067
Karlin,713.3052610000001
Lenell,702.2653700000001
Jaleen,700.570415
Amory,698.662333
Loghan,692.9096959999999
Kemani,692.781324
Aarin,692.676825
Elizah,692.517245
Maysen,689.180053
Yu,683.489357
Bergen,682.925024
Jalani,673.616259
Jamille,673.479423
Adama,672.7146700000001
Laray,665.522256
Sully,665.5176230000001
Latrelle,665.308862
Onnie,664.3572230000001
Khanh,662.75548
Amil,661.8052309999999
Braylyn,661.5521769999999
Tanay,661.063212
Kailan,659.232761
Caelin,659.158099
Alexandr,656.239956
Daryan,656.138076
Wallis,654.622062
Kelechi,648.648494
Javonne,646.051594
Gean,645.994681
Kao,645.458334
Cypress,642.7546150000001
Tamari,639.3206610000001
Evann,634.337944
Tarren,632.9670070000001
Jeffie,627.715909
Amel,625.482374
Jaspreet,623.708833
Amen,623.660314
Neema,617.783584
Hien,613.08858
Lorren,612.715537
Jonel,612.6505480000001
Kelyn,610.6906190000001
Jodeci,608.1752389999999
Alexy,607.478474
Jayln,606.543254
Chayanne,601.107466
Brittain,598.385006
Selby,595.1274549999999
Akili,591.896442
Kimari,591.479976
Anmol,590.472412
Kirin,590.139974
Min,589.129682
Eri,587.186027
Bralyn,582.7695570000001
Alyn,582.742595
Osie,580.951667
Shiva,580.950328
Kamerin,580.5293320000001
Pheonix,578.3514309999999
Abrar,576.900756
Darnelle,573.536531
Haydin,572.946492
Davonne,559.431911
Makana,556.047924
Ayomide,554.577639
Daine,554.4028099999999
Avrey,541.782016
Truth,541.390661
Uchenna,539.67233
Gracin,537.3083839999999
Chong,536.896691
Marrion,536.009629
Atley,535.308139
Luverne,534.767742
Lunden,534.0009610000001
Manpreet,533.557713
Kodee,533.325804
Kyri,530.500126
Donnelle,530.2115980000001
Koree,529.952254
Riyan,528.259191
Sagan,526.849373
Teran,523.613117
Avory,522.6795549999999
Lior,520.632626
Hoa,519.884708
Alexx,519.454611
Arleigh,515.496346
Brier,514.257293
Lyndall,513.4221719999999
Terin,510.907222
Kallan,509.422604
Maika,505.69662800000003
Trayce,504.464568
Deavion,502.71614500000004
Indy,501.475923
Ellington,500.417504
Feliz,498.52877800000005
Alexiz,498.397451
Neftaly,498.13695199999995
Kaegan,495.71034000000003
Edris,495.269629
Harpreet,495.17132000000004
Jailin,489.922734
Mackinley,489.57928499999997
Kendle,489.30663
Donyae,487.302887
Koi,485.358666
Eastyn,483.916571
Vertis,483.07369800000004
Shady,480.399537
Shondell,480.066762
Monti,479.724204
Ardie,478.622326
Londen,476.61620700000003
Kayde,476.54545099999996
Gabryel,476.224649
Chai,475.69343399999997
Gurpreet,475.593432
Tomie,473.437588
Corley,472.934632
Mishael,469.77639000000005
Shalin,469.497742
Shann,465.46971399999995
Lyndal,462.991251
Jamani,461.954209
Chee,460.36613
Deshay,460.06831900000003
Devlyn,459.95008600000006
Royale,457.35648899999995
Jaidin,450.60592
Dayan,449.43750300000005
Jari,447.90736
Amarii,445.04145700000004
Dilyn,444.089446
Yuval,441.627245
Toryn,441.53306
Rajah,441.09779800000007
Tatem,438.83986500000003
Chidera,438.68247599999995
Amarri,437.771104
Rielly,436.043049
Bobie,435.77100099999

## 4: Convert the string to a list
### Instructions
Use the split() method that strings have to split on the new-line delimiter ("\n") and assign the resulting list to data_list. Then use the print() function to display the first 5 elements in data_list.
### Answer

In [2]:
f = open('dq_unisex_names.csv', 'r')
data = f.read()
data_list = data.split("\n")
print(data_list[:5])

['Casey,176544.328149', 'Riley,154860.66517300002', 'Jessie,136381.830656', 'Jackie,132928.78874000002', 'Avery,121797.41951600001']

## 5: Convert the list of strings to a list of lists
### Instructions
Split each element in data_list on the comma delimiter (,) and append the resulting list to string_data.

To accomplish this:

* create an empty list and assign it to string_data
* write a for loop that iterates over data_list
* within the loop body, run the split() method on each element to return a list (you call that list comma_list)
* within the loop body, run the append() method to add each list (comma_list) to string_data.

Finally, use the print() function to display the first 5 elements in string_data.
### Answer

In [3]:
f = open('dq_unisex_names.csv', 'r')
data = f.read()
data_list = data.split('\n')

string_data = []
for data_elm in data_list:
    comma_list = data_elm.split(",")
    string_data.append(comma_list)
    
print(string_data[:5])

[['Casey', '176544.328149'], ['Riley', '154860.66517300002'], ['Jessie', '136381.830656'], ['Jackie', '132928.78874000002'], ['Avery', '121797.41951600001']]

## 6: Convert numerical values
### Instructions
Create a new list of lists called numerical_data where:

* the value at index 0 for each list is the unisex name (as a string)
* the value at index 1 for each list is the number of people who share that name (as a float)
To accomplish this:

* create an empty list and assign to numerical_data
* write a for loop that iterates over string_data
* in the loop body
    * retrieve the value at index 0 and assign to a variable
    * retrieve the value at index 1, convert it to a float, and assign to a variable
    * create a new list containing these 2 values (in the same order)
* use the append() method to add this new list to numerical_data.
Finally, display the first 5 elements in numerical_data.
### Answer

In [9]:
numerical_data = []
for str_elm in string_data:
    if len(str_elm) != 2:
        continue
    name = str_elm[0]
    num = float(str_elm[1])
    lst = [name, num]
    numerical_data.append(lst)
    
print(numerical_data[:5])

[['Casey', 176544.328149], ['Riley', 154860.66517300002], ['Jessie', 136381.830656], ['Jackie', 132928.78874000002], ['Avery', 121797.41951600001]]

## 7: Filter the list
### Instructions
Create a new list of strings called thousand_or_greater that contains just the names that at least a thousand people share.

To accomplish this:

* create an empty list and assign to thousand_or_greater
* write a for loop that iterates over numerical_data
* in the loop body, use an if statement to determine if the value at index 1 for that element (a list) is greater than or equal to 1000
* if the value is larger than or equal to 1000, use the append() method to add it to thousand_or_greater

Finally, display the first 10 elements in thousand_or_greater.
### Answer

In [11]:
# The last value is ~100 people
numerical_data[len(numerical_data)-1]

thousand_or_greater = []
for num in numerical_data:
    if num[1] >= 1000:
        thousand_or_greater.append(num[0])
        
print(thousand_or_greater[:10])

['Casey', 'Riley', 'Jessie', 'Jackie', 'Avery', 'Jaime', 'Peyton', 'Kerry', 'Jody', 'Kendall']